### ISSUE TITLE
[enhancement] 建议使用自建httpbin服务，提高tester速度

### ISSUE THREAD

**Issue by everhopingandwaiting** [Python3WebSpider/ProxyPool#109]
`docker-compose.yml`

```yml

services:
  httpbin_server:
    image: kennethreitz/httpbin
    container_name: httpbin_server
    ports:
      - "30008:80"
    restart: always

```
