### ISSUE TITLE
[Question]Redis Hash表是否能存储代理键值信息

### ISSUE THREAD

**Issue by cyicz123** [Python3WebSpider/ProxyPool#161]
个人通过自身体验以及Issues相关问题，认为增加每个代理ip详情信息（如位置，延迟时间等）很有必要。

然后本人阅读了**ProxyPool**的redis源码，想增加一个存放详情信息的表。由于对redis知识不了解，在查阅资料以后，我认为可以增加一个hash表存放每个proxy的详情键值对。相关逻辑如下：
1. 添加proxy时，在hash表中，以proxy为key，相关信息键值对为value，添加详情信息的数据。
2. 当需要删除proxy时，删除对应hash表中的proxy。

想请问一下作者，这样的逻辑是否可以。如果可以，我将开始开发，然后添加我的PR。由于我对开源合作流程不是很理解，可能需要作者指导。

**Comment by Germey** [comment]
多谢建议，这样做是可行的。目前我只用了 zset 来存储了代理信息，你可以仿照 https://github.com/Python3WebSpider/ProxyPool/blob/master/proxypool/storages/redis.py 添加一个类似的 hash 表的操作类，然后 proxy 为 key，value 是详情的序列化结果。

非常感谢贡献！有问题可以随时留言。

**Comment by cyicz123** [comment]
你好，目前本人在开发过程中遇到了redis表设计的问题，特向您咨询。
目前个人redis设计如下所示（以yaml格式呈现结构）：
```yaml
REDIS_SCORE_KEY:
    proxy1: score
    ......
    proxyn: score

REDIS_DETAIL_KEY:
    proxy1: json_str
        ......
    proxyn: json_str
```
在**REDIS_DETAIL_KEY**中，每个键为代理proxy的字符串，值为代理信息的json字符串，每个json字符串格式如下：
```json
{
    "proxy": "8.8.8.8:8888",
    "location": "shanghai", 
    "delay": 0.2,
    "some details": "etc."
}
```
但是考虑到通过redis查询一些信息，然后筛选满足条件的代理的功能。例如，通过redis筛选出location在shanghai的代理。
我认为下面的表设计是不是更适合一些：
```
REDIS_SCORE_KEY:
    proxy1: score
    ......
    proxyn: score

proxy1:
    location: shanghai
    delay: 0.2
    some details: etc.
......
proxyn:
    ......
```
即直接在redis中存储各个键值对，而不是上面先将代理信息的字典转化为json字符串作为代理的值存入redis中。

由于本人是redis的初学者，没有什么经验。请问您是否有更好的建议呢？

**Comment by cyicz123** [comment]
另外阐述一下，我想贡献开发实现的功能：
- [ ]  增加代理详情信息
- [ ]  能够通过RESTful api风格对代理进行查询
- [ ]  另开一个仓库，fork yacd仓库，然后修改源码实现proxypool的ui面板，效果类似clash代理的ui面板

**Comment by Germey** [comment]
非常感谢！

个人建议：
* 关于 score 好像你直接打算弃用 zset，该用 hash 了吗？这样代理就无法根据分数自动排序了，所以关于代理分数那块个人建议保持 zset。
* 关于代理信息的存储，的确，个人觉得不用 JSON 序列化会更加方便处理些，当然用 JSON 序列化也没有什么大问题，只不过在存取的时候得全部读出和写入。个人觉得用前者，配合一个统一前缀比较好（有专属前缀相当于 keys 是一个 group，防止和其他项目冲突），类似：
```
proxypool:proxy1:
    location: shanghai
    delay: 0.2
    some details: etc.
......
proxypool:proxyn:
    ......
```

**Comment by Germey** [comment]
> 另外阐述一下，我想贡献开发实现的功能：
> 
> * [ ]   增加代理详情信息
> * [ ]   能够通过RESTful api风格对代理进行查询
> * [ ]   另开一个仓库，fork yacd仓库，然后修改源码实现proxypool的ui面板，效果类似clash代理的ui面板

多谢！我觉得这几个功能都挺好的，多谢贡献，如有问题请随时留言。

**Comment by cyicz123** [comment]
你好，我并没有修改score的zset表，我的思路是从原先的score表中取出代理，然后在新建的details表中通过代理字段查询代理的详情信息。但是我的疑问是：新建的detail表是应该选择如下哪种层次结构。
```yaml
REDIS_DETAIL_KEY:
    proxy1: 
        location: shanghai
        delay: 0.2
        some details: etc.
        ......
    proxyn: 
        location: shanghai
        delay: 0.2
        some details: etc.
```
还是这种，用proxy作为主键。
```yaml
proxy1: 
    location: shanghai
    delay: 0.2
    some details: etc.
    ......
proxyn: 
    location: shanghai
    delay: 0.2
    some details: etc.
```
请问，redis支持多层级的键值组合吗？
